### ISSUE TITLE
Check if user email is taken when a user attempts to register

### ISSUE THREAD

**Issue by rbclark** [mitre-cyber-academy/ctf-scoreboard#126]
Looks like we never added any validations to make sure that a user email doesn't already exist before allowing them to attempt to register. Should be easy enough to validate this.

```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(<email>) already exists.

  active_record/connection_adapters/postgresql_adapter.rb:614:in `async_exec'
    @connection.async_exec(sql, type_casted_binds)
  active_record/connection_adapters/postgresql_adapter.rb:614:in `block (2 levels) in exec_no_cache'
    @connection.async_exec(sql, type_casted_binds)
  active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
    yield
  active_support/concurrency/share_lock.rb:185:in `yield_shares'
    yield
  active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
    @lock.yield_shares(compatible: [:load]) do
...
(118 additional frame(s) were not displayed)

ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(<email>) already exists.
: INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "confirmation_token", "confirmation_sent_at", "full_name", "affiliation", "year_in_school", "gender", "area_of_study", "state") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "id"

ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email"
DETAIL:  Key (email)=(<email>) already exists.
: INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "confirmation_token", "confirmation_sent_at", "full_name", "affiliation", "year_in_school", "gender", "area_of_study", "state") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING "id"
```

**Comment by rbclark** [comment]
Fixed in 7341685351f50531d060c216d83eab55a1de2ecf
